spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice_db
    username: appuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: info
