-- Extend invoice with new fields
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS billing_address TEXT;
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS terms VARCHAR(20);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS tags VARCHAR(255);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS message_on_invoice TEXT;
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS message_on_statement TEXT;

-- Extend invoice_item with new fields
ALTER TABLE invoice_item ADD COLUMN IF NOT EXISTS service_date DATE;
ALTER TABLE invoice_item ADD COLUMN IF NOT EXISTS product_or_service VARCHAR(100);

-- Attachments table
CREATE TABLE IF NOT EXISTS invoice_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(150),
    size BIGINT NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoice_attachment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(id) ON DELETE CASCADE
);
